### ISSUE TITLE
Zombie.js: visit with options is deprecated and will be removed soon

### ISSUE THREAD

**Issue by repat** [repat/Grafari#34]
Ich habe gerade aufgrund des Herumschiebens von @thinking-aloud neulich meine node modules neu installiert und bekam die Meldung

> visit with options is deprecated and will be removed soon

**Comment by xiaoshao** [comment]
Which will be used to instead of 'visit'?

**Comment by LennartRoeder** [comment]
@xiaoshao too bad we wrote this in German :(.
Anyway, we decided not to update our zombie.js version, since it was just a student project for last semester. What you can do though is, to pass your options as an object.
